name: "🚨 Availability Event"
description: Report an availability event
title: "[Issue Notice] YYYY-MM-DD - {brief description of event}"
labels: ["service availability"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        See https://health.aws.amazon.com/health/status for AWS health
  - type: dropdown
    id: status
    attributes:
      label: Current status of the event
      options:
        - Ongoing
        - In recovery
        - Resolved
    validations:
      required: true
      
