name: "🚨 Availability Event"
description: Report an availability event
title: "[Issue Notice] YYYY-MM-DD - {brief description of event}"
labels: ["service availability"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        See https://health.aws.amazon.com/health/status for AWS health

  - type: markdown  
    id: description
    attributes:
      label: Describe the availability event
      description: A clear and concise description of the event.
    validations:
      required: true
      
  - type: input
    id: start_time
    attributes:
      label: YYYY/MM/DD hh:mm UTC
      description: Start Date and Time (UTC)
    validations:
      required: true

  - type: markdown  
    id: timeline
    attributes:
      label: Event timeline
      description: Times when events occurred
      value: |
        1. 10/20/2025 12:00 AM UTC ...
        2. ...


  - type: markdown  
    id: alarms
    attributes:
      label: Relevant Alarm Thresholds Breached
      description: Description of alarms and thresholds which were breached

- type: dropdown
  id: status
  attributes:
    label: Current status of the event
    options:
      - Ongoing
      - In recovery
      - Resolved
  validations:
    required: true
      
